language: node_js
node_js: 16.13.1
cache: npm

before-script:
  - npm i
  - npm i -g surge

script:
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: artur-cicd-app.surge.sh
  on:
    all_branches: true